### ISSUE TITLE
example without `goinit` (using pre-authenticated credential file)

### ISSUE THREAD

**Issue by maxogden** [cyverse/gocommands#1]
can this be used by passing a credentials file and avoiding have to `goinit` on fresh machine?

**Comment by iychoi** [comment]
You don't need to perform `goinit`. You can directly call `goput` or `goget` with `-c` option.
I'll add an example in README soon.

**Comment by iychoi** [comment]
Updated README.

Also, added support for reading configurations from a YAML/JSON file or environmental variables. Please check out README.
