### ISSUE TITLE
a usability feature request that would might lead to an easier transition for existing icommand users

### ISSUE THREAD

**Issue by edwins** [cyverse/gocommands#12]
Being an long-time user of icommands and then switching to gocommands, I find myself wanting to use the icommand equivalent for a gocommand subcommands For example, I find myself wanting to do this:

`gocmd icd`
`gocmd ils`

As a cognitive convenience, it would be nice if gocmmands accepted both forms for a command e.g. `gocmd cd` and `gocmd icd` to perform a listing.

**Comment by iychoi** [comment]
Gotcha. I'll add them as aliases.

**Comment by iychoi** [comment]
Added at the commit `bd9d9d9`
