### ISSUE TITLE
additional encryption option, --encrypt-filename

### ISSUE THREAD

**Issue by trel** [cyverse/gocommands#27]
When using the new `--encrypt` option (https://github.com/cyverse/gocommands/commit/9bc2f49f7e2bf98fb569e0b4664cd781d600804e)... the filename is obfuscated/lost.

Feels like this should not be the default behavior, but is still useful.

Consider making this functionality available via `--encrypt-filename` as an additional flag.

--

Does `get` work the same way?   Would it need to have a similar flag?  Not sure on that...

**Comment by iychoi** [comment]
Yes, I'm working on it now.

**Comment by iychoi** [comment]
The latest commit 36709d2137ed17c847e9002485e18a679e5104d9 will add `--encrypt_filename` flag for the purpose.

`get` command also has the same flags to decrypt filename and content.
