### ISSUE TITLE
Support IRODS_ENVIRONMENT_FILE environment variable

### ISSUE THREAD

**Issue by tedgin** [cyverse/gocommands#3]
This is a feature request.  

When using iCommands, the environment variable `IRODS_ENVIRONMENT_FILE` comes in handy. It makes switching between iRODS zones easier. Instead of editing `~/.irods/irods_environment.json` or changing a handful of other environment variables, just a single environment variable needs to be changed to switch to another zone. It would be nice if gocommands could support this as well.

**Comment by iychoi** [comment]
The new release, v0.4.0, supports `iRODS_ENVIRONMENT_FILE`.
