### ISSUE TITLE
Feature request: add/modify/remove metadata

### ISSUE THREAD

**Issue by jjkoehorst** [cyverse/gocommands#30]
Thanks for all the fixes :)

A small request and I am not sure if this is within the scope of gocmd but I was wondering is metadata support planned in the future?
So that you can add/remove metadata from data objects and collections.

**Comment by iychoi** [comment]
Sure, I'll figure it out :-)

**Comment by iychoi** [comment]
The new release v0.9.3 includes `lsmeta`, `addmeta`, and `rmmeta`.
https://github.com/cyverse/gocommands/releases/tag/v0.9.3
