### ISSUE TITLE
Two irods environments --config option

### ISSUE THREAD

**Issue by jjkoehorst** [cyverse/gocommands#32]
I wanted to switch from one environment to another but the -c option is ignored?

gocmd init --config ~/.irods_wur/irods_wur.json
iRODS Host [unlock-icat.irods.surfsara.nl]:

While the content of this is 

"irods_host": "scomp0000.wurnet.nl",

does $IRODS_HOST take over when that is set? Not sure what the official order was nowadays when you explicitly give a config file.

**Comment by jjkoehorst** [comment]
Should have checked indeed $IRODS_HOST takes over... is that preferred?

**Comment by iychoi** [comment]
![capture1](https://github.com/cyverse/gocommands/assets/4394097/1930a736-7b2d-4706-8e59-c037dbc3ea50)

the `-c` or `--config` flag actually reads config from the file given. Can you double check if it really is an issue?

**Comment by jjkoehorst** [comment]
Did you try with setting IRODS_HOST to something else?

**Comment by iychoi** [comment]
The result above didn't set any environmental variables.

![capture2](https://github.com/cyverse/gocommands/assets/4394097/dcbabda9-edc1-43f0-a6c6-00b1a85ade31)

If I set the environmental varaible `IRODS_HOST`, it will overwrite configuration provided. Environmental variables have the highest priority setting configuration values in iCommands and GoCommands.

**Comment by jjkoehorst** [comment]
Yeah I wanted to double check

 - default json from standard location
- System variables override default json
- Manual set of json overrides system variables 

is then not the case but it is 

 - default json from standard location
- Manual set of json overrides standard location
- System variables override default json

then I just need to make sure I unset system variables on a local device when working with multiple config files. Thanks!

**Comment by iychoi** [comment]
Yes, the priority was set to address this issue. 

https://github.com/cyverse/gocommands/issues/23


Thanks for testing.
