### ISSUE TITLE
Skip if file exists (do not ask option) for automatic retrieval

### ISSUE THREAD

**Issue by jjkoehorst** [cyverse/gocommands#37]
For automatic download retrieval is there a way to have a skip already exists option or force download if file size does not match but if it does match skip?

https://github.com/cyverse/gocommands/blob/d06587740afafd51b5bf5f78eaa5fae37e074cf1/cmd/subcmd/get.go#L357

**Comment by jjkoehorst** [comment]
Testing to see if gocmd sync might actually be what we need.

**Comment by iychoi** [comment]
There's `-f` flag to try.

**Comment by jjkoehorst** [comment]
Will try when I get behind my laptop. Does that not force download? As sometimes you want to skip the download when it exists in some form.

**Comment by iychoi** [comment]
If your purpose is skip downloading the same file that already exists at local, `--diff` and `--no_hash` will compare file size and skip. `gocmd sync` also uses the same feature internally.
