### ISSUE TITLE
sync to local fails if the provided directory doesn't exist

### ISSUE THREAD

**Issue by mstfdkmn** [cyverse/gocommands#39]
Synching from irods to local works as long as the provided directory is available in the local file system or a single dot (current working dir) is passed. Providing a local directory name that doesnt exist as destination blocks the synch starts.

```
root@01882c953a26:/# gocmd sync i:test_col my_dir
File or dir '/my_dir' not found!

Error Trace:
  - failed to perform sync (from iRODS to local):
    github.com/cyverse/gocommands/cmd/subcmd.processSyncCommand
        /github/workspace/cmd/subcmd/sync.go:108
  - failed to make new target path for get i:test_col to my_dir:
    github.com/cyverse/gocommands/cmd/subcmd.processGetCommand
        /github/workspace/cmd/subcmd/get.go:141
  - data object/collection not found for path /my_dir
```

Synching from local to irods like the case above works normal.

**Comment by iychoi** [comment]
Fixed in the new release v0.9.12

https://github.com/cyverse/gocommands/releases/tag/v0.9.12
