### ISSUE TITLE
seems not possible to upload a file with a new name

### ISSUE THREAD

**Issue by mstfdkmn** [cyverse/gocommands#40]
I cannot not upload a local file as another object name to irods. The subcommand always uses the filename in the source.

`gocmd put test.txt another.txt`

**Comment by mstfdkmn** [comment]
FYI: this is same for the download too:
```
[mustafa@dev-u0137480 ~]$ ./gocmd get test.py test1.py
file /home/mustafa/test.py already exists. Overwrite? [y/n]:
```

**Comment by iychoi** [comment]
This is fixed in the new release.
https://github.com/cyverse/gocommands/releases/tag/v0.9.11
