### ISSUE TITLE
gocmd sync --no_hash shows no "progress"

### ISSUE THREAD

**Issue by jjkoehorst** [cyverse/gocommands#44]
When running gocmd sync with the no_hash option there is no progress shown.
It would be nice to know what bit has been doing, how many files have been processed or some form of activity.

**Comment by iychoi** [comment]
The request is very vague to me. `no_hash` option is not intended to show any progress. But it's for ignoring hash comparison between local and server files. 

If you want to get a list of files transferred and their size/hash, I'm already working on it. Check out issue #41 .
