### ISSUE TITLE
Automatic option for remove bundle

### ISSUE THREAD

**Issue by jjkoehorst** [cyverse/gocommands#45]
We are trying to automate the sync process but in the end there is a question about old bundle file.

`removing old bundle file  /unlock/home/bdp_robot/gridion/.gocmd_staging/bundle_dcf97665bee10acf627d2e7e622c9efc.tar found. Delete? [y/n]: `

Is there a way to say yes automatically?

**Comment by iychoi** [comment]
Currently, no. I'll add `-f` flag soon to do so. 
Alternatively, you can try `bclean` command with `-f` to clean up old bundle files before running `bput`. The "old bundle files` are bundle files not deleted in the previous run due to failures or etc. So `bclean` is a command to delete them.

**Comment by iychoi** [comment]
The new release will remove bundle without asking user input when `-f` is given.
https://github.com/cyverse/gocommands/releases/tag/v0.9.11
