### ISSUE TITLE
Add a flag to ignore hidden files starting with `.` in the filenames

### ISSUE THREAD

**Issue by iychoi** [cyverse/gocommands#46]
Add a flag to ignore hidden files starting with `.` in the filenames

**Comment by trel** [comment]
or a flag to *show* the default-hidden dotfiles...

**Comment by iychoi** [comment]
I think we should add a flag to exclude rather than include to keep compatibility with icommands.

**Comment by iychoi** [comment]
Implemented in v0.9.12
https://github.com/cyverse/gocommands/releases/tag/v0.9.12
