### ISSUE TITLE
touch/create command

### ISSUE THREAD

**Issue by mstfdkmn** [cyverse/gocommands#47]
Hi,
I am using gocommands mostly to test some operations in irods. It would have been useful to have `touch/create` command that will create an empty object if doesn't exist and if exists will change the mtime of that data object. For my own usage locally,  I made a subcommand - `touch`- that calls `CreateDataObject` and `CloseDataObject`. But this way is not calling the touch api to update the mtime. Seems no function is available in [go-irodsclient](https://github.com/cyverse/go-irodsclient/blob/main/fs/fs.go) yet that will call the touch api. Thanks.

**Comment by iychoi** [comment]
Implemented in v0.9.12
https://github.com/cyverse/gocommands/releases/tag/v0.9.12
